# PLUGINS
# =======
source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "andreyorst/plug.kak" noload

plug "andreyorst/smarttab.kak" defer smarttab %{
    set-option global softtabstop 4  # backspace deletes 4 spaces
} config %{
    hook global WinSetOption filetype=.* expandtab  # tab inserts 4 spaces
}

plug "andreyorst/fzf.kak" %{
    map global normal <c-p> ": fzf-mode<ret>" -docstring "enter fzf-mode"
    set-option global fzf_file_command "fd --follow"
    set-option global fzf_cd_command "fd --follow --type directory"
}

plug "alexherbo2/auto-pairs.kak" %{
    map global user "s" ": auto-pairs-surround<ret>" -docstring "surround selection"
    # hook global WinCreate .* auto-pairs-enable
}

plug "ul/kak-lsp" do %{
    # upgrade kak-lsp through homebrew (brew upgrade kak-lsp)
    ln -sf target/release/kak-lsp ~/.cargo/bin/
} config %{
    hook global WinSetOption filetype=(python|rust) %{
        lsp-enable-window
    }
    map global user "l" ": enter-user-mode lsp<ret>" -docstring "LSP mode"
}


# COMMON
# ======
set-option global tabstop 4
set-option global indentwidth 4
# auto reload the buffers when an external modification is detected
set-option global autoreload yes



# APPEARANCE
# ==========
add-highlighter global/ show-matching
add-highlighter global/ show-whitespaces -spc " " -lf " "


# MAPPINGS
# ========
map global user "c" ": comment-line<ret>"   -docstring "Comment/Uncomment selection"
map global user "n" ": toggle-numbers<ret>" -docstring "Toggle line numbers"
map global user "w" ": toggle-wrap<ret>"    -docstring "Toggle soft line wrap"

# Yank and Paste to system clipboard
hook global NormalKey y|d|c %{ nop %sh{ printf %s "$kak_main_reg_dquote" | pbcopy }}
map global normal P "! pbpaste<ret>"
map global normal p "<a-!> pbpaste<ret>"

# Use tab/s-tab to cycle completions
hook global InsertCompletionShow .* %{
    map window insert <tab> <c-n>
    map window insert <s-tab> <c-p>
}
hook global InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <s-tab> <c-p>
}


# COMMANDS
# ========
define-command toggle-wrap -docstring "Toggle soft line wrap" %{
    try %{
        add-highlighter buffer/wrap wrap -word -indent -marker "↪" -width 88
    } catch %{
        remove-highlighter buffer/wrap
    }
}

define-command toggle-numbers -docstring "Toggle line numbers" %{
    try %{
        add-highlighter buffer/numbers number-lines -hlcursor -separator " "
    } catch %{
        remove-highlighter buffer/numbers
    }
}

# define-command -docstring "Split vertically" sp %{
#   tmux-terminal-vertical kak -c %val{session}
# }

# define-command -docstring "Split horizontally" vs %{
#   tmux-terminal-horizontal kak -c %val{session}
# }


