# PLUGINS
# =======
source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "andreyorst/plug.kak" noload

plug "andreyorst/smarttab.kak" defer smarttab %{
    set-option global softtabstop 4  # backspace deletes 4 spaces
} config %{
    hook global WinSetOption filetype=.* expandtab  # tab inserts 4 spaces
}

plug "andreyorst/fzf.kak" %{
    map global normal <c-p> ": fzf-mode<ret>" -docstring "enter fzf-mode"
    set-option global fzf_file_command "fd --follow"
    set-option global fzf_cd_command "fd --follow --type directory"
}

plug "alexherbo2/auto-pairs.kak" %{
    map global user "s" ": auto-pairs-surround<ret>" -docstring "surround selection"
    # hook global WinCreate .* auto-pairs-enable
}

plug "ul/kak-lsp" do %{
    ln -sf target/release/kak-lsp ~/.cargo/bin/
} config %{
    hook global WinSetOption filetype=(python|rust) %{
        lsp-enable-window
    }
}


# COMMON
# ======
set-option global tabstop 4
set-option global indentwidth 4


# APPEARANCE
# ==========
hook global WinCreate .* %{
    add-highlighter window/matching show-matching
    add-highlighter window/show-whitespaces show-whitespaces -spc " " -lf " "
}


# MAPPINGS
# ========
map global user "c" ": comment-line<ret>" -docstring "comment/uncomment selection"

# yank to clipboard
hook global NormalKey y|d|c %{ nop %sh{ printf %s "$kak_main_reg_dquote" | pbcopy }}

# tab/s-tab to cycle completions
hook global InsertCompletionShow .* %{
    map window insert <tab> <c-n>
    map window insert <s-tab> <c-p>
}
hook global InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <s-tab> <c-p>
}


# COMMANDS
# ========
define-command toggle-wrap -docstring "toggle soft wrap" %{
    try %{
        add-highlighter window/wrap wrap -word -indent -marker "↪" -width 88
    } catch %{
        remove-highlighter window/wrap
    }
}

define-command toggle-numbers -docstring "toggle soft numbers" %{
    try %{
        add-highlighter window/numbers number-lines -hlcursor -separator " "
    } catch %{
        remove-highlighter window/numbers
    }
}
