[user]
email = "21958895+benburk@users.noreply.github.com"
username = "benburk"

[init]
defaultBranch = "main"

[delta]
side-by-side = true

[core]
editor = "hx"
pager = "delta"
excludesfile = "~/.gitignore_global"
