[user]
email = "123149780+chariotsofiron@users.noreply.github.com"
username = "chariotsofiron"

[init]
defaultBranch = "main"

[delta]
side-by-side = true

[core]
editor = "hx"
pager = "delta"
excludesfile = "~/.gitignore_global"
