set-option global tabstop 4


###########
# PLUGINS #
###########
source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "andreyorst/plug.kak" noload

plug "andreyorst/smarttab.kak" %{
    set-option global softtabstop 4  # backspace deletes 4 spaces
    hook global WinSetOption filetype=(rust|markdown|kak|python|sh) expandtab
    hook global WinSetOption filetype=(makefile|gas) noexpandtab
    hook global WinSetOption filetype=(c|cpp) smarttab
}


eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(python|rust) %{
    lsp-enable-window
}

# yank to clipboard
hook global NormalKey y|d|c %{ nop %sh{ printf %s "$kak_main_reg_dquote" | pbcopy }}


############
# COMMANDS #
############
define-command toggle-wrap -docstring 'toggle soft wrap' %{
    try %{
        add-highlighter window/wrap wrap -word -indent -marker '↪' -width 88
    } catch %{
        remove-highlighter window/wrap
    }
}

define-command toggle-numbers -docstring 'toggle soft numbers' %{
    try %{
        add-highlighter window/numbers number-lines -hlcursor -separator ' '
    } catch %{
        remove-highlighter window/numbers
    }
}
