set-option global tabstop 4

###########
# PLUGINS #
###########
source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "andreyorst/plug.kak" noload

plug "andreyorst/smarttab.kak" %{
    set-option global softtabstop 4  # backspace deletes 4 spaces
    hook global WinSetOption filetype=(rust|markdown|kak|python|sh) expandtab
    hook global WinSetOption filetype=(makefile|gas) noexpandtab
    hook global WinSetOption filetype=(c|cpp) smarttab
}


# eval %sh{kak-lsp --kakoune -s $kak_session}
# lsp-enable

eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(python) %{
    lsp-enable-window
}