[tool.ruff]
select = ["ALL"]
ignore = [
    "T201", # print
    "D213", # multi-line-summary-second-line
    "D203", # one-blank-line-before-class
    "D401", # first line of docstring should be in imperative mood
    "INP001", # implicit namespace package

    # disabled to make formatter happy
    "COM812", # missing-trailing-comma
    "ISC001", # single-line-implicit-string-concatenation
    "FA102", # import annotations
]

[tool.ruff.format]
skip-magic-trailing-comma = true
