[tool.black]
line-length = 88
skip_magic_trailing_comma = true

[tool.isort]
profile = "black"
multi_line_output = 3
float_to_top = true

[tool.mypy]
# see what this enables with mypy --help | grep -A 8 'Strict mode;'
strict = true
no_implicit_reexport = false # causes lag and issues with spacy
disallow_any_explicit = true
show_column_numbers = true
show_error_codes = true

[tool.pylint.MASTER]
# http://pylint.pycqa.org/en/latest/technical_reference/extensions.html
# enable-all-extensions maybe?
load-plugins = [
    "pylint.extensions.broad_try_clause",
    "pylint.extensions.code_style",
    "pylint.extensions.emptystring",
    "pylint.extensions.comparetozero",
    "pylint.extensions.comparison_placement",
    "pylint.extensions.confusing_elif",
    "pylint.extensions.for_any_all",
    "pylint.extensions.consider_ternary_expression",
    "pylint.extensions.bad_builtin",
    "pylint.extensions.mccabe",
    "pylint.extensions.docstyle",
    "pylint.extensions.check_elif",
    "pylint.extensions.eq_without_hash",
    "pylint.extensions.private_import",
    "pylint.extensions.overlapping_exceptions",
    "pylint.extensions.docparams",
    "pylint.extensions.docstyle",
    "pylint.extensions.empty_comment",
]
output-format = "colorized"  # add colors to output
default-docstring-type = "sphinx"

[tool.pylint.messages_control]
disable = [
    "logging-fstring-interpolation",
    "compare-to-zero",
    "no-member",  # handled by mypy's attr-defined
    "missing-module-docstring",
    "wrong-import-order",  # handled by isort
    
]
good-names = "i,j,k,_,T"

[tool.pylint.similarities]
ignore-imports = true  # Ignore imports when computing similarities.

[tool.pytest.ini_options]
python_files = "*.py"
