export ZSH="$HOME/.oh-my-zsh"
export PATH="/usr/local/opt/python/libexec/bin/:$PATH"

ZSH_THEME="robbyrussell"

plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

FZF_DEFAULT_COMMAND='fd --follow --no-ignore-vcs""'
FZF_CTRL_T_COMMAND=$FZF_DEFAULT_COMMAND
FZF_ALT_C_COMMAND='fd --follow --no-ignore-vcs --type directory ""'
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
